### ISSUE TITLE
Splitting by timeBucket does not work

### ISSUE THREAD

**Issue by arrawatia** [facetjs/facetjs#20]
` facet('demo').split(facet("time").timeBucket("PT1H", "Etc/UTC"), "Time")` fails with the following error :

```
/Users/xyz/code/src/facetjs-old/node_modules/chronology/build/chronology.js:548
                throw new TypeError("Duration JS must be a string");
                      ^
TypeError: Duration JS must be a string
    at Function.Duration.fromJS (/Users/xyz/code/src/facetjs-old/node_modules/chronology/build/chronology.js:548:23)
    at Function.TimePeriodSplit.fromJS (/Users/xyz/code/src/facetjs-old/build/facet.js:8083:53)
    at Function.FacetSplit.fromJS (/Users/xyz/code/src/facetjs-old/build/facet.js:7825:37)
    at new FacetQuery (/Users/xyz/code/src/facetjs-old/build/facet.js:6839:55)
    at Function.FacetQuery.fromJS (/Users/xyz/code/src/facetjs-old/build/facet.js:6884:20)
    at legacyTranslator (/Users/xyz/code/src/facetjs-old/build/facet.js:12162:28)
    at Array.Core.legacyDriver [as 0] (/Users/xyz/code/src/facetjs-old/build/facet.js:12262:31)
    at ActionsExpression.Expression.compute (/Users/xyz/code/src/facetjs-old/build/facet.js:1322:40)
    at Object.<anonymous> (/Users/xyz/code/src/facetjs-old/docs/examples/example3_druid.js:47:4)
    at Module._compile (module.js:456:26)
```

The full code is here :  https://gist.github.com/arrawatia/1a43780c0206f2d76ee4

I ran a debugger and found out the dates and time stamps are parsed twice : Once when the expressions are compiled and again when the expression is run by calling `compute()`. 

The method works fine when compiling the expression but fails on compute.

**Comment by vogievetsky** [comment]
Hi I am sorry for the delay, I have been reworking the query planner and it should be all done now. The latest version `0.9.8` has about 4k diff from what you were using including native druid querying infrastructure. (No more need to wrap the legacy driver, that was a hack anyway).

You can find an example of the new querying here: https://github.com/facetjs/facetjs/blob/master/test/functional/druidQueries.mocha.coffee

A perk of the new code is that it can now simulate and 'preview' the query plan by calling `.simulateQueryPlan(context)` you can see it in action here: https://github.com/facetjs/facetjs/blob/master/test/core/overall/simulate.mocha.coffee

This is useful for diagnostics as it allows a peak into the queries bing generated behind the scenes.

I am also going to adjust your code slightly (remove references to legacy driver) and post it here. Please let me know if it works.

(Note: The docs on the site now all need to be updated with the latest)

**Comment by vogievetsky** [comment]
I have tried to update your example to work: https://gist.github.com/vogievetsky/870d02becee6ff24cd3c
I can not test it directly because I do not have access to your druid cluster but I think it should work. I am going to update all the docs right now.
